### ISSUE TITLE
Sunnuntai demo

### ISSUE THREAD

**Issue by jviding** [Matoking/KillMuumi#1]
Moro!
Meikä ei valitettavasti ehdi tänää mitenkään paikalle.
Readmesta löytyy linkki multiplayer muumipeliin, mutta se on
vielä aika kesken. Muut pelaajat näkyy, mutta en ehtiny saada
ammusten ja muiden pelaajien collisionia toimimaan.
Onnea demoon!
-Jasu

**Comment by emillaine** [comment]
Mul sama, heräsin vast just äske ni veikkaan etten ehtis demoon mitenkää järkevästi.

Eli rock the demo, @Matoking!

**Comment by Matoking** [comment]
Viilasin peliä hieman mutta muuten demosin samaa peliä mitä ennen aamuviittä pelattiin. Naurusta päätellen tykkäsivät pelistä. :)

Koitan pitää sen antamani linkin käytössä vielä jonkin aikaa, mutta luultavasti siirrän pelin ennen pitkään johonkin muuhun osoitteeseen.

**Comment by emillaine** [comment]
:+1:

**Comment by Matoking** [comment]
Peli löytyy nyt osoitteesta
http://matoking.com/killmuumi
